services:
  nibepi:
    build: .
    container_name: nibepi
    restart: unless-stopped
    ports:
      - "1880:1880"
    devices:
      - "/dev/serial/by-id/usb-XXXX:/dev/ttyUSB0"
    volumes:
      - nibepi-config:/etc/nibepi

volumes:
  nibepi-config:
